import type { SelectOption } from '../components/Select';

export const countries: SelectOption[] = [
  { id: 'AF', label: 'Afghanistan' },
  { id: 'AL', label: 'Albania' },
  { id: 'DZ', label: 'Algeria' },
  { id: 'AR', label: 'Argentina' },
  { id: 'AM', label: 'Armenia' },
  { id: 'AU', label: 'Australia' },
  { id: 'AT', label: 'Austria' },
  { id: 'AZ', label: 'Azerbaijan' },
  { id: 'BH', label: 'Bahrain' },
  { id: 'BD', label: 'Bangladesh' },
  { id: 'BE', label: 'Belgium' },
  { id: 'BO', label: 'Bolivia' },
  { id: 'BA', label: 'Bosnia and Herzegovina' },
  { id: 'BR', label: 'Brazil' },
  { id: 'BG', label: 'Bulgaria' },
  { id: 'KH', label: 'Cambodia' },
  { id: 'CM', label: 'Cameroon' },
  { id: 'CA', label: 'Canada' },
  { id: 'CL', label: 'Chile' },
  { id: 'CN', label: 'China' },
  { id: 'CO', label: 'Colombia' },
  { id: 'CR', label: 'Costa Rica' },
  { id: 'HR', label: 'Croatia' },
  { id: 'CY', label: 'Cyprus' },
  { id: 'CZ', label: 'Czech Republic' },
  { id: 'DK', label: 'Denmark' },
  { id: 'DO', label: 'Dominican Republic' },
  { id: 'EC', label: 'Ecuador' },
  { id: 'EG', label: 'Egypt' },
  { id: 'SV', label: 'El Salvador' },
  { id: 'EE', label: 'Estonia' },
  { id: 'ET', label: 'Ethiopia' },
  { id: 'FI', label: 'Finland' },
  { id: 'FR', label: 'France' },
  { id: 'GE', label: 'Georgia' },
  { id: 'DE', label: 'Germany' },
  { id: 'GH', label: 'Ghana' },
  { id: 'GR', label: 'Greece' },
  { id: 'GT', label: 'Guatemala' },
  { id: 'HN', label: 'Honduras' },
  { id: 'HK', label: 'Hong Kong' },
  { id: 'HU', label: 'Hungary' },
  { id: 'IS', label: 'Iceland' },
  { id: 'IN', label: 'India' },
  { id: 'ID', label: 'Indonesia' },
  { id: 'IE', label: 'Ireland' },
  { id: 'IL', label: 'Israel' },
  { id: 'IT', label: 'Italy' },
  { id: 'JM', label: 'Jamaica' },
  { id: 'JP', label: 'Japan' },
  { id: 'JO', label: 'Jordan' },
  { id: 'KZ', label: 'Kazakhstan' },
  { id: 'KE', label: 'Kenya' },
  { id: 'KW', label: 'Kuwait' },
  { id: 'LV', label: 'Latvia' },
  { id: 'LB', label: 'Lebanon' },
  { id: 'LT', label: 'Lithuania' },
  { id: 'LU', label: 'Luxembourg' },
  { id: 'MY', label: 'Malaysia' },
  { id: 'MT', label: 'Malta' },
  { id: 'MX', label: 'Mexico' },
  { id: 'MD', label: 'Moldova' },
  { id: 'MN', label: 'Mongolia' },
  { id: 'ME', label: 'Montenegro' },
  { id: 'MA', label: 'Morocco' },
  { id: 'MZ', label: 'Mozambique' },
  { id: 'MM', label: 'Myanmar' },
  { id: 'NP', label: 'Nepal' },
  { id: 'NL', label: 'Netherlands' },
  { id: 'NZ', label: 'New Zealand' },
  { id: 'NI', label: 'Nicaragua' },
  { id: 'NG', label: 'Nigeria' },
  { id: 'MK', label: 'North Macedonia' },
  { id: 'NO', label: 'Norway' },
  { id: 'OM', label: 'Oman' },
  { id: 'PK', label: 'Pakistan' },
  { id: 'PA', label: 'Panama' },
  { id: 'PY', label: 'Paraguay' },
  { id: 'PE', label: 'Peru' },
  { id: 'PH', label: 'Philippines' },
  { id: 'PL', label: 'Poland' },
  { id: 'PT', label: 'Portugal' },
  { id: 'QA', label: 'Qatar' },
  { id: 'RO', label: 'Romania' },
  { id: 'RW', label: 'Rwanda' },
  { id: 'SA', label: 'Saudi Arabia' },
  { id: 'SN', label: 'Senegal' },
  { id: 'RS', label: 'Serbia' },
  { id: 'SG', label: 'Singapore' },
  { id: 'SK', label: 'Slovakia' },
  { id: 'SI', label: 'Slovenia' },
  { id: 'ZA', label: 'South Africa' },
  { id: 'KR', label: 'South Korea' },
  { id: 'ES', label: 'Spain' },
  { id: 'LK', label: 'Sri Lanka' },
  { id: 'SE', label: 'Sweden' },
  { id: 'CH', label: 'Switzerland' },
  { id: 'TW', label: 'Taiwan' },
  { id: 'TZ', label: 'Tanzania' },
  { id: 'TH', label: 'Thailand' },
  { id: 'TN', label: 'Tunisia' },
  { id: 'TR', label: 'Turkey' },
  { id: 'UA', label: 'Ukraine' },
  { id: 'AE', label: 'United Arab Emirates' },
  { id: 'GB', label: 'United Kingdom' },
  { id: 'US', label: 'United States' },
  { id: 'UY', label: 'Uruguay' },
  { id: 'UZ', label: 'Uzbekistan' },
  { id: 'VE', label: 'Venezuela' },
  { id: 'VN', label: 'Vietnam' },
  { id: 'ZM', label: 'Zambia' },
  { id: 'ZW', label: 'Zimbabwe' },
];

export function getCountryLabel(id: string): string {
  return countries.find((c) => c.id === id)?.label ?? id;
}
